# Autogenerated wrapper script for libcircle_jll for riscv64-linux-gnu-mpi+mpich
export libcircle

using CompilerSupportLibraries_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("libcircle")
JLLWrappers.@declare_library_product(libcircle, "libcircle.so.2")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libcircle,
        "lib/libcircle.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
